// ===== App Store States =====

export const APP_STORE_STATES = {
  // Submission states
  PREPARE_FOR_SUBMISSION: 'PREPARE_FOR_SUBMISSION',
  WAITING_FOR_REVIEW: 'WAITING_FOR_REVIEW',
  IN_REVIEW: 'IN_REVIEW',
  PENDING_DEVELOPER_RELEASE: 'PENDING_DEVELOPER_RELEASE',
  PROCESSING_FOR_APP_STORE: 'PROCESSING_FOR_APP_STORE',

  // Rejection states
  REJECTED: 'REJECTED',
  DEVELOPER_REJECTED: 'DEVELOPER_REJECTED',
  METADATA_REJECTED: 'METADATA_REJECTED',
  INVALID_BINARY: 'INVALID_BINARY',

  // Live states
  READY_FOR_SALE: 'READY_FOR_SALE',

  // Other states
  ACCEPTED: 'ACCEPTED',
  DEVELOPER_REMOVED_FROM_SALE: 'DEVELOPER_REMOVED_FROM_SALE',
  REMOVED_FROM_SALE: 'REMOVED_FROM_SALE',
  REPLACED_WITH_NEW_VERSION: 'REPLACED_WITH_NEW_VERSION',

  // Compliance states
  PENDING_CONTRACT: 'PENDING_CONTRACT',
  WAITING_FOR_EXPORT_COMPLIANCE: 'WAITING_FOR_EXPORT_COMPLIANCE',
  NOT_APPLICABLE_FOR_REVIEW: 'NOT_APPLICABLE_FOR_REVIEW',
} as const;

export type AppStoreState = (typeof APP_STORE_STATES)[keyof typeof APP_STORE_STATES];

export const BUILD_NUMBER_INCREMENTABLE_STATES: readonly AppStoreState[] = [
  // Submission states
  APP_STORE_STATES.PREPARE_FOR_SUBMISSION,
  APP_STORE_STATES.WAITING_FOR_REVIEW,
  APP_STORE_STATES.IN_REVIEW,
  APP_STORE_STATES.PENDING_DEVELOPER_RELEASE,

  // Rejection states
  APP_STORE_STATES.REJECTED,
  APP_STORE_STATES.DEVELOPER_REJECTED,
  APP_STORE_STATES.METADATA_REJECTED,
  APP_STORE_STATES.INVALID_BINARY,

  // Other states
  APP_STORE_STATES.DEVELOPER_REMOVED_FROM_SALE,
];

// ===== Version Actions =====

export const VERSION_ACTION_TYPES = {
  CREATE_NEW_VERSION: 'new_version',
  INCREMENT_BUILD_NUMBER: 'increment_build',
} as const;

export type VersionActionType = (typeof VERSION_ACTION_TYPES)[keyof typeof VERSION_ACTION_TYPES];

// ===== Platform Types =====

export const PLATFORM_TYPES = {
  IOS: 'IOS',
  MAC_OS: 'MAC_OS',
  TV_OS: 'TV_OS',
} as const;

export type PlatformType = (typeof PLATFORM_TYPES)[keyof typeof PLATFORM_TYPES];

// ===== External Service Configuration =====

export const APP_STORE_CONNECT_API = {
  BASE_URL: 'https://api.appstoreconnect.apple.com/v1',
  TIMEOUT_MS: 30000,
} as const;

export const JWT_AUTHENTICATION = {
  ALGORITHM: 'ES256' as const,
  EXPIRATION_SECONDS: 20 * 60, // 20 minutes
  AUDIENCE: 'appstoreconnect-v1',
} as const;

// ===== Validation Patterns =====

export const SEMANTIC_VERSION_PATTERN = /^\d+\.\d+\.\d+$/;
