name: Test Action

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  call-my-action:
    runs-on: ubuntu-latest
    outputs:
      version_output: ${{ steps.my_action_step.outputs.version }}
      build_number_output: ${{ steps.my_action_step.outputs.buildNumber }}
      action_output: ${{ steps.my_action_step.outputs.action }}
      version_created_output: ${{ steps.my_action_step.outputs.versionCreated }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run my action
        id: my_action_step
        uses: ./
        with:
          issuer-id: ${{ secrets.ISSUER_ID }}
          key-id: ${{ secrets.KEY_ID }}
          key: ${{ secrets.KEY }}
          bundle-id: ${{ secrets.BUNDLE_ID }}
          platform: IOS
          create-new-version: false
      - name: Print outputs (call-my-action job)
        run: |
          echo "Version: ${{ steps.my_action_step.outputs.version }}"
          echo "Build Number: ${{ steps.my_action_step.outputs.buildNumber }}"
          echo "Action: ${{ steps.my_action_step.outputs.action }}"
          echo "Version Created: ${{ steps.my_action_step.outputs.versionCreated }}"

  use-action-outputs:
    runs-on: ubuntu-latest
    needs: call-my-action
    steps:
      - name: Use outputs from previous job
        run: |
          echo "Version from previous job: ${{ needs.call-my-action.outputs.version_output }}"
          echo "Build Number from previous job: ${{ needs.call-my-action.outputs.build_number_output }}"
          echo "Action from previous job: ${{ needs.call-my-action.outputs.action_output }}"
          echo "Version Created from previous job: ${{ needs.call-my-action.outputs.version_created_output }}"
